services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3601:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: PhoneFolio
    volumes:
      - ./Database:/var/lib/mysql